using UnityEngine;

namespace Lighthouse.Editor.ScriptableObject
{
    /// <summary>
    /// Settings for temporary game objects generated during scene editing.
    /// These are generated by SceneEditProcessor and are not saved to the scene assets.
    /// </summary>
    public class SceneEditSettings : UnityEngine.ScriptableObject
    {
        [SerializeField] bool enableSceneEditProcess = true;

        [SerializeField] GameObject canvasSceneEditorOnlyObject;

        [SerializeField] string editorOnlyObjectName = "__EditorOnly__";

        public bool EnableSceneEditProcess => enableSceneEditProcess;

        public GameObject CanvasSceneEditorOnlyObject => canvasSceneEditorOnlyObject;

        public string EditorOnlyObjectName => editorOnlyObjectName;
    }
}
